#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod address_upgradeable;
pub mod blake_3_sol;
pub mod byte_strings;
pub mod console;
pub mod console_2;
pub mod context_upgradeable;
pub mod ed_25519;
pub mod erc1155_upgradeable;
pub mod erc165_upgradeable;
pub mod erc1967_proxy;
pub mod erc1967_upgrade;
pub mod erc1967_upgrade_upgradeable;
pub mod i_beacon;
pub mod i_beacon_upgradeable;
pub mod i_themelio_bridge;
pub mod ierc1155_metadata_uri_upgradeable;
pub mod ierc1155_receiver_upgradeable;
pub mod ierc1155_upgradeable;
pub mod ierc165_upgradeable;
pub mod ierc1822_proxiable;
pub mod ierc1822_proxiable_upgradeable;
pub mod initializable;
pub mod proxy;
pub mod sha_512;
pub mod std_error;
pub mod std_math;
pub mod std_storage;
pub mod storage_slot;
pub mod storage_slot_upgradeable;
pub mod strings;
pub mod themelio_bridge;
pub mod themelio_bridge_proxy;
pub mod uups_upgradeable;
pub mod vm;
