name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    container:
      image: rustembedded/cross:x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2

#      - uses: actions/cache@v2
#        with:
#          path: |
#            ~/.cargo/bin/
#            ~/.cargo/registry/index/
#            ~/.cargo/registry/cache/
#            ~/.cargo/git/db/
#            target/
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Musl Build
        run: cargo build --target x86_64-unknown-linux-musl --verbose